# Generated by Django 5.2.3 on 2025-06-24 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_tag_product_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='tags',
            field=models.ManyToManyField(to='products.tag', verbose_name='<UNK> <UNK>'),
        ),
    ]
