# Generated by Django 5.2.3 on 2025-07-03 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_category_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='tags',
            field=models.ManyToManyField(blank=True, to='products.tag', verbose_name='Теги категорий'),
        ),
    ]
