# Generated by Django 5.1.5 on 2025-07-03 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_productimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='slug',
            field=models.SlugField(default='slugg', max_length=255, unique=True, verbose_name='URL-слаг'),
            preserve_default=False,
        ),
    ]
